import type { Recipe } from "@/types/recipe";

export const MOCK_RECIPES: Recipe[] = [
  {
    id: "1",
    title: "토마토 파스타",
    description: "신선한 토마토와 바질의 조화",
    category: "noodle",
    ingredients: [
      { name: "스파게티 면", amount: "200", unit: "g" },
      { name: "토마토", amount: "3", unit: "개" },
      { name: "마늘", amount: "4", unit: "쪽" },
      { name: "올리브오일", amount: "3", unit: "큰술" },
      { name: "바질", amount: "5", unit: "잎" },
      { name: "소금", amount: "약간" },
    ],
    cookTimeMinutes: 25,
    difficulty: "easy",
    servingCount: 2,
    createdAt: "2025-03-10T12:00:00Z",
  },
  {
    id: "2",
    title: "연어 구이 with 레몬 버터 소스",
    description: "부드러운 연어와 상큼한 레몬 버터",
    category: "grill",
    ingredients: [
      { name: "연어 필렛", amount: "2", unit: "조각" },
      { name: "버터", amount: "30", unit: "g" },
      { name: "레몬", amount: "1", unit: "개" },
      { name: "딜", amount: "약간" },
      { name: "소금", amount: "약간" },
      { name: "후추", amount: "약간" },
    ],
    cookTimeMinutes: 35,
    difficulty: "medium",
    servingCount: 2,
    createdAt: "2025-03-09T14:30:00Z",
  },
  {
    id: "3",
    title: "김치찌개",
    description: "든든한 한 그릇",
    category: "soup_stew",
    ingredients: [
      { name: "묵은지", amount: "200", unit: "g" },
      { name: "돼지고기 목살", amount: "150", unit: "g" },
      { name: "두부", amount: "1/2", unit: "모" },
      { name: "대파", amount: "1", unit: "대" },
      { name: "고춧가루", amount: "1", unit: "큰술" },
      { name: "다진 마늘", amount: "1", unit: "큰술" },
    ],
    cookTimeMinutes: 40,
    difficulty: "easy",
    servingCount: 4,
    createdAt: "2025-03-08T09:00:00Z",
  },
  {
    id: "4",
    title: "제육볶음",
    description: "매콤달콤한 밥도둑",
    category: "stir_fry",
    ingredients: [
      { name: "돼지고기 앞다리살", amount: "300", unit: "g" },
      { name: "양파", amount: "1", unit: "개" },
      { name: "대파", amount: "1", unit: "대" },
      { name: "고추장", amount: "2", unit: "큰술" },
      { name: "간장", amount: "1", unit: "큰술" },
      { name: "설탕", amount: "1", unit: "큰술" },
      { name: "다진 마늘", amount: "1", unit: "큰술" },
    ],
    cookTimeMinutes: 30,
    difficulty: "easy",
    servingCount: 3,
    createdAt: "2025-03-07T16:00:00Z",
  },
  {
    id: "5",
    title: "갈비찜",
    description: "특별한 날의 메뉴",
    category: "steam",
    ingredients: [
      { name: "소갈비", amount: "1", unit: "kg" },
      { name: "감자", amount: "2", unit: "개" },
      { name: "당근", amount: "1", unit: "개" },
      { name: "간장", amount: "5", unit: "큰술" },
      { name: "설탕", amount: "3", unit: "큰술" },
      { name: "배즙", amount: "3", unit: "큰술" },
    ],
    cookTimeMinutes: 90,
    difficulty: "hard",
    servingCount: 4,
    createdAt: "2025-03-06T10:00:00Z",
  },
  {
    id: "6",
    title: "감자조림",
    description: "반찬으로 딱 좋은",
    category: "braise",
    ingredients: [
      { name: "감자", amount: "3", unit: "개" },
      { name: "간장", amount: "3", unit: "큰술" },
      { name: "설탕", amount: "1", unit: "큰술" },
      { name: "물엿", amount: "1", unit: "큰술" },
      { name: "참기름", amount: "1", unit: "작은술" },
    ],
    cookTimeMinutes: 25,
    difficulty: "easy",
    servingCount: 4,
    createdAt: "2025-03-05T12:00:00Z",
  },
];
