import type { Recipe } from "@/types/recipe";

export const MOCK_RECIPES: Recipe[] = [
  {
    id: "1",
    title: "토마토 파스타",
    description: "신선한 토마토와 바질의 조화",
    category: "noodle",
    sourceType: "url",
    sourceUrl: "https://example.com/tomato-pasta",
    ingredients: [
      { name: "스파게티 면", amount: "200", unit: "g" },
      { name: "토마토", amount: "3", unit: "개" },
      { name: "마늘", amount: "4", unit: "쪽" },
      { name: "올리브오일", amount: "3", unit: "큰술" },
      { name: "바질", amount: "5", unit: "잎" },
      { name: "소금", amount: "약간" },
    ],
    cookingSteps: [
      { order: 1, description: "끓는 물에 소금을 넣고 스파게티 면을 삶는다." },
      { order: 2, description: "토마토를 십자로 칼집 내고 끓는 물에 데쳐 껍질을 벗긴다." },
      { order: 3, description: "올리브오일에 마늘을 볶다가 토마토를 넣고 소스를 만든다.", tip: "약불에서 천천히 졸여야 맛이 깊어진다." },
      { order: 4, description: "삶은 면을 소스에 넣고 버무린 뒤 바질을 올린다." },
    ],
    nutritionInfo: {
      calories: 450,
      carbohydrates: 62,
      protein: 14,
      fat: 16,
    },
    cookTimeMinutes: 25,
    difficulty: "easy",
    servingCount: 2,
    createdAt: "2025-03-10T12:00:00Z",
  },
  {
    id: "2",
    title: "연어 구이 with 레몬 버터 소스",
    description: "부드러운 연어와 상큼한 레몬 버터",
    category: "grill",
    sourceType: "image",
    ingredients: [
      { name: "연어 필렛", amount: "2", unit: "조각" },
      { name: "버터", amount: "30", unit: "g" },
      { name: "레몬", amount: "1", unit: "개" },
      { name: "딜", amount: "약간" },
      { name: "소금", amount: "약간" },
      { name: "후추", amount: "약간" },
    ],
    cookingSteps: [
      { order: 1, description: "연어에 소금, 후추를 뿌려 밑간한다." },
      { order: 2, description: "팬에 올리브오일을 두르고 연어 껍질 면부터 굽는다.", tip: "껍질이 바삭해질 때까지 뒤집지 않는다." },
      { order: 3, description: "뒤집어서 1분 더 구운 뒤 꺼낸다." },
      { order: 4, description: "같은 팬에 버터와 레몬즙을 넣어 소스를 만든다." },
      { order: 5, description: "연어에 소스를 끼얹고 딜을 올려 마무리한다." },
    ],
    nutritionInfo: {
      calories: 380,
      carbohydrates: 2,
      protein: 34,
      fat: 26,
    },
    cookTimeMinutes: 35,
    difficulty: "medium",
    servingCount: 2,
    createdAt: "2025-03-09T14:30:00Z",
  },
  {
    id: "3",
    title: "김치찌개",
    description: "든든한 한 그릇",
    category: "soup_stew",
    sourceType: "manual",
    ingredients: [
      { name: "묵은지", amount: "200", unit: "g" },
      { name: "돼지고기 목살", amount: "150", unit: "g" },
      { name: "두부", amount: "1/2", unit: "모" },
      { name: "대파", amount: "1", unit: "대" },
      { name: "고춧가루", amount: "1", unit: "큰술" },
      { name: "다진 마늘", amount: "1", unit: "큰술" },
    ],
    cookingSteps: [
      { order: 1, description: "돼지고기를 한입 크기로 썰어 볶는다." },
      { order: 2, description: "김치를 넣고 함께 볶다가 물을 붓고 끓인다." },
      { order: 3, description: "고춧가루, 다진 마늘을 넣고 중불에서 20분 끓인다." },
      { order: 4, description: "두부와 대파를 넣고 5분 더 끓인다." },
    ],
    nutritionInfo: {
      calories: 320,
      carbohydrates: 12,
      protein: 22,
      fat: 20,
    },
    cookTimeMinutes: 40,
    difficulty: "easy",
    servingCount: 4,
    createdAt: "2025-03-08T09:00:00Z",
  },
  {
    id: "4",
    title: "제육볶음",
    description: "매콤달콤한 밥도둑",
    category: "stir_fry",
    sourceType: "url",
    sourceUrl: "https://example.com/jeyuk-bokkeum",
    ingredients: [
      { name: "돼지고기 앞다리살", amount: "300", unit: "g" },
      { name: "양파", amount: "1", unit: "개" },
      { name: "대파", amount: "1", unit: "대" },
      { name: "고추장", amount: "2", unit: "큰술" },
      { name: "간장", amount: "1", unit: "큰술" },
      { name: "설탕", amount: "1", unit: "큰술" },
      { name: "다진 마늘", amount: "1", unit: "큰술" },
    ],
    cookingSteps: [
      { order: 1, description: "고추장, 간장, 설탕, 다진 마늘로 양념장을 만든다." },
      { order: 2, description: "돼지고기를 양념장에 30분 이상 재운다.", tip: "시간이 없으면 15분이라도 재워야 맛이 밴다." },
      { order: 3, description: "팬에 기름을 두르고 양파를 먼저 볶는다." },
      { order: 4, description: "재운 고기를 넣고 센 불에서 빠르게 볶는다." },
      { order: 5, description: "대파를 넣고 마무리한다." },
    ],
    nutritionInfo: {
      calories: 420,
      carbohydrates: 18,
      protein: 28,
      fat: 26,
    },
    cookTimeMinutes: 30,
    difficulty: "easy",
    servingCount: 3,
    createdAt: "2025-03-07T16:00:00Z",
  },
  {
    id: "5",
    title: "갈비찜",
    description: "특별한 날의 메뉴",
    category: "steam",
    sourceType: "image",
    ingredients: [
      { name: "소갈비", amount: "1", unit: "kg" },
      { name: "감자", amount: "2", unit: "개" },
      { name: "당근", amount: "1", unit: "개" },
      { name: "간장", amount: "5", unit: "큰술" },
      { name: "설탕", amount: "3", unit: "큰술" },
      { name: "배즙", amount: "3", unit: "큰술" },
    ],
    cookingSteps: [
      { order: 1, description: "갈비를 찬물에 1시간 담가 핏물을 뺀다." },
      { order: 2, description: "끓는 물에 갈비를 넣고 5분간 데쳐 불순물을 제거한다." },
      { order: 3, description: "간장, 설탕, 배즙으로 양념장을 만든다." },
      { order: 4, description: "냄비에 갈비와 양념장을 넣고 중불에서 40분 끓인다.", tip: "중간에 뒤집어줘야 골고루 맛이 밴다." },
      { order: 5, description: "감자, 당근을 넣고 20분 더 끓인다." },
    ],
    nutritionInfo: {
      calories: 580,
      carbohydrates: 35,
      protein: 42,
      fat: 28,
    },
    cookTimeMinutes: 90,
    difficulty: "hard",
    servingCount: 4,
    createdAt: "2025-03-06T10:00:00Z",
  },
  {
    id: "6",
    title: "감자조림",
    description: "반찬으로 딱 좋은",
    category: "braise",
    sourceType: "manual",
    ingredients: [
      { name: "감자", amount: "3", unit: "개" },
      { name: "간장", amount: "3", unit: "큰술" },
      { name: "설탕", amount: "1", unit: "큰술" },
      { name: "물엿", amount: "1", unit: "큰술" },
      { name: "참기름", amount: "1", unit: "작은술" },
    ],
    cookingSteps: [
      { order: 1, description: "감자를 깍둑썰기하여 물에 담가 전분을 뺀다." },
      { order: 2, description: "냄비에 감자, 간장, 설탕, 물엿, 물을 넣고 끓인다." },
      { order: 3, description: "중약불로 줄이고 국물이 자작해질 때까지 조린다.", tip: "너무 세게 저으면 감자가 부서진다." },
      { order: 4, description: "불을 끄고 참기름을 둘러 마무리한다." },
    ],
    nutritionInfo: {
      calories: 180,
      carbohydrates: 38,
      protein: 3,
      fat: 2,
    },
    cookTimeMinutes: 25,
    difficulty: "easy",
    servingCount: 4,
    createdAt: "2025-03-05T12:00:00Z",
  },
];
